apiVersion: v1
kind: Namespace
metadata:
  name: kuberay-cluster
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kuberay
  namespace: flux-system
spec:
  interval: 4h
  url: https://ray-project.github.io/kuberay-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kuberay-cluster
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=kuberay-cluster}
  chart:
    spec:
      chart: ray-cluster
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: kuberay
      version: "1.1.0"
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    preserveValues: true
  values: {}

