apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-secrets
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
    policies.kyverno.io/title: Sync Secrets
    policies.kyverno.io/category: FluxCD
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/description: "Secrets like registry credentials often need to exist in multiple Namespaces so Pods there have access. Manually duplicating those Secrets is time consuming and error prone. This policy will copy a Secret called `docker-hub-regcred` which exists in the `flux-system` Namespace to new Namespaces when they are created. It will also push updates to the copied Secrets should the source Secret be changed.            "
spec:
  generateExistingOnPolicyUpdate: true
  rules:
  - name: sync-image-pull-secret
    match:
      resources:
        kinds:
        - Namespace
    generate:
      apiVersion: v1
      kind: Secret
      name: docker-hub-regcred
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      clone:
        namespace: flux-system
        name: docker-hub-regcred
