apiVersion: v1
kind: Namespace
metadata:
  name: redis
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 4h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=redis}
  chart:
    spec:
      chart: redis
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: ${redis_version}
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    preserveValues: true
  values:
    global:
      redis:
        password: "5241590000000000"
