apiVersion: v1
kind: Namespace
metadata:
  name: uptrace
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: uptrace
  namespace: flux-system
spec:
  interval: 4h
  url: https://charts.uptrace.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptrace
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=uptrace}
  chart:
    spec:
      chart: uptrace
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: uptrace
      version: ${uptrace_version}
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    preserveValues: true
