kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:VeuIyhrIVDlbG4eqrF0y70K8Cm9oT/+iOQYUs9pwfp6wIurCABCJcvqkjYWl7fYkRcTz,iv:UHcNSl/xooZGYMRTT/elEhebmmKNLdsBAeTbgadHi+U=,tag:jEDyAJTOIEj1RI3NOKBZsw==,type:str]
    github_user: ENC[AES256_GCM,data:LI/9WpizKhOPDMPX,iv:pyRvURqWuvCbkowspdMCYHXRazk4cQytkaYw6Hl5KC4=,tag:y/pK7+U+XOK36OfGBCTO2w==,type:str]
    github_api_token: ENC[AES256_GCM,data:sFmrqP/KEthrrhlKxoRrsZJW0uO+NT1U3yU2oxBDAuW9qlB9E02/cQ==,iv:njeV8OJfy/BsSAJec3V+1+OBcGWxEvGgcZ/bVy5I5fU=,tag:I73sC5jtjkhP/LzpRglNww==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:XbvbxMP/oyYSt9Y=,iv:fhZQr3JC8E14qzxcyU4AtCQU81Col791IZas4AuAdqo=,tag:zey8RlgSl0h9SD2zZIgXFg==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:0RGIxwuUFQ05lFBIe97csVfGfo+TtBxWm+JGjCtSzWs0FCXl,iv:LTE84CaI+xCANpXUqEdZJjEW54FtHy3q4Gx0fMZU3JQ=,tag:+TUbjRvdG6fuAshozCNbmg==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:4HShUrxLzq/hX478Cw==,iv:e3qH5idGzTMLiJU4bXCdJBVd5adWkI3dKF8qxIgYgVc=,tag:wqAgqhB23NzNXKdtNhbvRg==,type:str]
    prism_central_user: ENC[AES256_GCM,data:IA4BUEA=,iv:BCoSWnJg+nUSn/PCbVnfmPasA0P/22ANZDVxHKDgUDg=,tag:EnyrBKwLTshB0FJZ4X+pWA==,type:str]
    prism_central_password: ENC[AES256_GCM,data:cnVmzFvtB4pLnA==,iv:NacvPPRy1m0POkLSrKATRK5Aw2I4bp9zZlkTVemYwtk=,tag:/Sz4cZ9ysIp4PuVQYo1/zQ==,type:str]
    objects_host: ENC[AES256_GCM,data:y21fx2XUzstMK+kB1A==,iv:1NFMJC8D9eQGtRWmgPX2BEMvJ7p/NKT5OK0rtfh2keU=,tag:JfbL5cmCZu6+KZ5GJWBnJw==,type:str]
    objects_port: ENC[AES256_GCM,data:GRQ=,iv:L1juio2NagzU50roSv/SDf9sm413LmjMjsW/TxQ2vts=,tag:+o0IZbEsFT2LPe83Hhxmpw==,type:str]
    objects_region: ENC[AES256_GCM,data:ODpPnt3ZzBFH,iv:BegN5m8CQjZ4WfFiB0p+Br3ruUf9lEceNuiE6h1KlbM=,tag:mUNhsPPqeN9f51/J7NAF9Q==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:7NvXtj4=,iv:I/MSeZ3zmKu8EQgN+lJW5IykAXnxaJ3n7/kgbrR6NSM=,tag:8ZV0ho/W5mtTfnSPkSxXLw==,type:str]
    objects_access_key: ENC[AES256_GCM,data:3S/4wiAEtn7Qhan+85OXtT92vqjmijKM05Qh242GLSk=,iv:SqeiW4oukc9wTgjpL8BN7Pea/ixYnH4jvH4y3lFK+TA=,tag:xsTk7zxM78bCW6p+Trjq1w==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:+L9owbpbeKoUh4jh2ehJEH0raxFLBLtNgg8JqRPTolA=,iv:CSJE05AzegHXZGbOp4o6rB1TBPILLsd8XANRwSCGzgM=,tag:A9chCQpYfoFNJEyQXKhwgA==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:va7kxc6KUnmy+lDT4NMpscdBWoT3+6Rs4+Sf,iv:zfpSsm8L1hU+DhpK5eAgFhEWkdjNwxhLaQC9InHhaUk=,tag:o6uOL6tnmEul1Cg5hwwWPw==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:4Xm3cgNufHOHi9/b3BHSEQ==,iv:0fqzBkVu8LiAJfB6thfRLT0MZUNxTTk2sxPkSMRSCfM=,tag:Zf5dJ9+6b42IKtqirKXBww==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:YvimccBxzUlrR3B69o2uqs4=,iv:RpO9Ecla2RuN8eSvObv3Znlqnswb5e61T8jZUqgWCW0=,tag:7tboHC/jJ2qi2XDomb8SeQ==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:ksW1gd7oeetpLom3IJ3x3Zgk3w==,iv:eYw+QWfImqt2fwrGTHgrB86gNbkhrQSiyys6o4rUGfE=,tag:Ym2gDvHE910KMhoW+gkByg==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:ox37+Q/6IkMQ+3gx/1ESCA==,iv:zpOdhSuPGHYcyY7yIUWuTcbZd0LkFlYfCsYXUoW5Uqg=,tag:RHhOS9APkGG7LEgE+lmPEw==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:YGPXInR97aewfcCcBM2jHixbIQpR,iv:yZh8sQ9kZkY2tpodQb9xc5kTkYJyPWb2VeyGFnHLNzk=,tag:H+BN26L2a4ASkvUetWhDIA==,type:str]
    huggingFaceToken: ENC[AES256_GCM,data:OzOHyNJq/LHuhuBTFSWE3vmzbweGo8OHsi7IygjwrUfcqm+vCg==,iv:PgNHZ5czFpM7Pi0qWgnxgndxM4xZW+Hs1Ff5WYVUExw=,tag:RHlnS7l7WRSc+JYJFukMyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1znw3q7j0drwhjyfvp5dmw59gpm5hrjc9lw3drpujslcjaky5veas2fmef4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bEF3TGlyUzgway9OK0di
            M2dmVS9KZmdCUTZrZnBmMHRrcEMzRnpXeWhFCnpKZFhnSmZVRzRXQVNUTjh4ZUcw
            eHFiR1FqcTRwYjYwZGFmbTRtM0R2WE0KLS0tIHNiMWNqN2g2Ris0b1IweG5yNFVu
            QUUreWU2QndFcUpPQlJuODlTTE9TY1EK0aAgFDOYWbr+A5Xwqjrj0RZ51O55pyu6
            vNfvHOkua/guxPJoMWD83pPt4ia8wI6Bo2MC76Tbh94+K2ohKusFXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-03T21:34:07Z"
    mac: ENC[AES256_GCM,data:r3E8yCQdgo5myGR6V51ULw27S8htSsRW1zrOn+qDir49vO2HKYYTGwl3OILqjH6Xh4u9Wy5zrg6CMVPD+yVBrUCohM3MwsElv9MgmwGviTLJHwY9cYAdATm6jyX/tHCGnb4SiCR+EiszHAQ9FnvModdcZtQpKu71/8EjI848tf8=,iv:C0Z89UtDkze2Q9hyeUhWpv5oVYJbqI9Z9gq1CnJq88g=,tag:LYNYDmlw72YXjNF2vtP0TQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
