kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:WYBRLaOAvsfnCqJPDWvr3w/siQ4oMHByibe5JBHmYtUOyBb5GZ7R3+hX71BN8uDQaAIa,iv:r1xLWj57viWuLFdL5lqR2QT6QAySTmTc+AhnlXkN4ro=,tag:YfwH5qU/IQjqH6Q2K9V/qQ==,type:str]
    github_user: ENC[AES256_GCM,data:VyV9AQcjYc+m1ymT,iv:Vysbto/M8a1eiCIe+frMuGZcSQVmpNBG9gsNWT/uHQM=,tag:PSdmiREvYcHLn9Urajhe9Q==,type:str]
    github_api_token: ENC[AES256_GCM,data:0QSg1CjAWz+97XmS+9vRZtYsJ3OXFrZ12c059Dww8RVfB4QtZIvEmQ==,iv:v1LydudrWW7aHu8Bmjd/Ihb76P0F13K8f/pgEJ/FflQ=,tag:WrK+LcjibG0TplnImliVVw==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:25SSg/oCkSx4sv0=,iv:t88TzPqFFLZa6eeGAs3EAb7CT08LZSYEEudZ64oIRVs=,tag:aMB2qaqp1RpQ2qZOJSa4sA==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:MZXSFcz5SoQBiWYSbFBanTunwWa1PEr3oVg7hev4TO6b4NbF,iv:rO5ycr5aqyHjPjCIFIZisnM8r7YtRShQchjbID4ZbgY=,tag:sgzb/SgH4W35U0iohnSx8g==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:kXlV5U0Y+1PUzFcj,iv:KXLMsCRtA+YzxqOUDSmlENyCAsK9GPO8KOwExLadJUk=,tag:QNjNuLGaFi0Fyuj86Wpw3A==,type:str]
    prism_central_user: ENC[AES256_GCM,data:/FPfGg/gSkxSt9JIuw==,iv:dbj1eNsXv0+/RQb+oXNtS2G2+8nJmQqmKfqr1EjFrok=,tag:KMSOyudjpSexWAeXpYek5Q==,type:str]
    prism_central_password: ENC[AES256_GCM,data:wm4dobQMOZ5TEA==,iv:sSk5IbEW7xO0zOxmg9MtZaH0JzZhP7iblOqbwTxUOHM=,tag:v1t7btmPwe1PD6bidWy2dA==,type:str]
    objects_host: ENC[AES256_GCM,data:fMGGf56e5Mvmc1C+Rw==,iv:kDG2HUCZaAiKDaIy9jpCf8r8gylCkCw5CbyDd15xzEA=,tag:0EWczYM2LXW8Fz8wVOco0Q==,type:str]
    objects_port: ENC[AES256_GCM,data:jtM=,iv:I4nykcEOSo7w7eijq8UAzolcZF2ipPIkK2LC0C8Ockg=,tag:Z9yy7l+DdndW5SvjV+7thQ==,type:str]
    objects_region: ENC[AES256_GCM,data:4dN7ewQPH1hM,iv:KUJsTqUe1FkR3ibMQogq5ZnyxkiaK7x/oN9dKBR08Lw=,tag:7ySRK8GqGnJCGaUe7sY/ng==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:TwAs2oU=,iv:aDmWJKkSucuZPpiPXdQnB8KW433euLfz90jnSHpHkjY=,tag:i4k3OCnzC7tr3lG7VLyPMA==,type:str]
    objects_access_key: ENC[AES256_GCM,data:BDUNPeCDFhMoz4TbI5CywNHNRY/yH+QI6jyAk/Ui0xs=,iv:hTXxkptb9AfP3JExvgGpm8LorePKWKWpl/wr3MMsXGU=,tag:V5BHMLAGBfveEuwS+oOiyw==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:ewjVRJzyoe81t5hFdaZqnVkZZ1A0WEfOyJRd5FwQzrA=,iv:IwlPB5eyzEfH4EWi+6ID7T6HGHP6AiDIMZQunUQC7Z4=,tag:EyI4miQpbocvbz6biB9qjg==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:4O2ptuL+s4ALMjRhUwsjACfyM5VZfG/rtD7I,iv:Bf51T4iYU8icgFVow3sUIp2SHIVZKKpxZHEG/cQ1pvY=,tag:ODg+3jJSTHmfKqtIzkQtww==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:8CIJ4BREF/6Ynu1+bK0dDQ==,iv:+qB+Jmmj4oV6XDrGdTM9b3bsbFM9xrr8XnwO4xob8FI=,tag:jMjpxpdeXa+WNX2IjcIHug==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:yErG13yx/7D+NmvFGEv/i/M=,iv:w6EzsY7ReWW4qcDuczZ+yoVrRIIxg15pb0BUuCUmVpE=,tag:M+EJhM5vJrITvJWfLIDVqg==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:Cqqm4XrxkWbI8+6VCg1qhVWl2Q==,iv:WWXGxirktrKuyFCmydyR2dlEYmUvJR9Em7M7PCDHYVU=,tag:v2SJ4A1FfYaZybkgLB46nA==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:qSg7QTcny9bkkgORGgMpuA==,iv:Aq2ZKhthB5UoUkqDLYb4bD4eJwN++vj/mCXhqFfLxAU=,tag:4Yc1WqKYAN1piJqowckRfg==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:aXSXDO313oC1khCNmXCkhztBw3Yp,iv:K9p3bhq5e8xf3JYkHWlrT5LoCrqfZMoQj4CpFl9+5iw=,tag:T6FHxzYeMhent+NrmnEZYg==,type:str]
    huggingFaceToken: ENC[AES256_GCM,data:piUQj2rb67Dq3itZe2/aJMN7f1/nAD5qZHC89d2zjY44SoCxqw==,iv:gIB2EW1jBVrg0+8OGyDeNxegu+ZpTmDy6zRktUC0yk0=,tag:lPJ95Qet5YbjlMHH5uW06w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1znw3q7j0drwhjyfvp5dmw59gpm5hrjc9lw3drpujslcjaky5veas2fmef4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmanU5QUJxcUdwWnpkcVd5
            aSs5bElOak53NWVBRjVSeDBNQnhnSktaMldvClZ0TjVZZzJsZHBXek9QOTdVeFZr
            NC9NSHRiWUYzUWFiRjUzaG9lamxueTAKLS0tIE1lQVVtblR0RHluTTBtbnhjaGd0
            dlZlcktiTkJuZ3ZHM2t2Zm1KWnkrZHcKCxSh9XohznXqgoI/249dgecYE5+JaaQ8
            W/vTBoTNSfoAsdt5wtrF36FB1hBKV8j8x/ciBLx1nMD4UMKct1rtDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-07T22:03:58Z"
    mac: ENC[AES256_GCM,data:c3HkCghJRiaGDWVE+cfQgYdZDu1peIbtKJnjhK/0dGmzaGNlSr5vGYE+H3/mRf/1Fz9tjzLaxyy96DD6K1H63PaeKmrY88CvBbEKaIS0tVHVsowwnzQV4m/VMHNXm303/kMOXVtbjnLzXIIiB8S17pOXi0zG0LuuqwGdJNzRQHw=,iv:OyJIH+QCMXhL8whN8DE3Sbn6ocJH1WS4wYYXOSvJGM4=,tag:ueCFuAXgIWeX+vs6WffDoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
