kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:VGb2sB9cbMuWOWZvcZStvZXW5hU+Q+Qm/csuK0MTlbKaXFd9l+LqZnTTJcIyO1RbrfjW,iv:81WH3ZFUv6ckLugPGKfMNlx2/T6EgI94ROIJIOhviiU=,tag:cGR9uDq5pcHrxwHpTsKIYQ==,type:str]
    github_user: ENC[AES256_GCM,data:Vvt51ZQ5K67X5g2p,iv:clFFRTHXFwZ2MW6MeeIj8DJpHMtkw7xI7izYtW+cLvQ=,tag:tmxfupVxJGWOialmWQBr1A==,type:str]
    github_api_token: ENC[AES256_GCM,data:e1OzeV87uBL330G8o7DNLVGHHsXGbQKiRN21RBZiJNJGp7eGAXa3bA==,iv:EuRZ+BDE/ygMSDy2j1fi+u0LgrjiW5GBlaQuBR4Gflg=,tag:vVr8plkdBZtdc4pVFSb4pA==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:9Zz1kousURlT4OE=,iv:mZUsV09qllNycZ8t3SZ5bsBjL/QoDiZbHUVFj0rtOx8=,tag:UroNbot0qzcgzqWbNQfQDQ==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:qcQE04LrKTItipKzYOheJJCcv2z+D0Blr0IYiXSXgE/M4nM+,iv:WDI3CX1zKM9XO5iUhfgyX/pLeF3GG6fYv9B2XHhXEJY=,tag:Rm34FPaQctyGEn3N5drHfg==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:CyKfZ2bAyhpKy9/y,iv:dvy3MX69L1imTeDrW4NZjs1RrdSMRL7AXnSq82w8cyY=,tag:x6F3NrQSdks55IxqH6DjBQ==,type:str]
    prism_central_user: ENC[AES256_GCM,data:3xiweAHi4/eLzoJ6Ow==,iv:xLCvhhguKHsGLshQW8Xmp/UhJfHrxrwjWHFahdu82mw=,tag:SGQYRKgteH/xnqz1xRaNaQ==,type:str]
    prism_central_password: ENC[AES256_GCM,data:9ZS/P4qm6jg3Dw==,iv:joVkKfV0FNMJ1ZO83WOvy4i7GRk4yipGT2vZwNfQuKs=,tag:LrGtDHG9Lsmk08+LzJDmWw==,type:str]
    objects_host: ENC[AES256_GCM,data:cUC3p9ivYEGtOx6XTQ==,iv:156g8kq+kD8tj57Ike95e76VnInshhcbqub4nrNbUO4=,tag:rh7rIAzBEZeYbKDmpr2mcw==,type:str]
    objects_port: ENC[AES256_GCM,data:4us=,iv:HH474MCuaA6qKR5bUpg8K0TXGyQ3KYwDvI4qiSTpH+0=,tag:GpzVfTnenNbfETi6mzzV+Q==,type:str]
    objects_region: ENC[AES256_GCM,data:8gFy/VziB/8z,iv:XtMoGFfuY2mTiolD+P5siE2hJmagBZUQnWVzZC4eOAs=,tag:WWuz/NTAyRf0FwWLUONp4A==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:ytG40AI=,iv:fFA91k7jgZqnjSxDNTO1d134GFv/scc4lQefK7OVqck=,tag:xQXSDY3ynwMy4xUZDBCD5Q==,type:str]
    objects_access_key: ENC[AES256_GCM,data:dZaGQYzO+C2UT50C1fiPX4Lt8yCrQCLM68uRwrEfi4g=,iv:H59MTuiEQN37s9HP418fPMvt/zrFo/KJHn1uKGr9jhc=,tag:610Wz/bOpODm+xxknnACjg==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:fVYX/mUr/KbK3YjjUKUEnG77ivTSqI84EV4oM0a/3HQ=,iv:4Z0H0tAW73VDz6yCFapxcfX616KIBKGMPjE3oTNJohk=,tag:JN5ir3pboUx2Ot2lPHp6Pg==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:i04mfwvhun5EHdiGCQfZC4Dl/XxPMxPvk37c,iv:e6EgzuKC+7RPbXyVPZ6pfaNB4RQr+TgY75Nw/VsEZF0=,tag:km20PDhLg3naJ1frsYvolw==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:GgWKKo17I/dre4u6Oe7R9g==,iv:NL+YvXDV+CRdnWlKnvDFVRq6CJb/cOUnt7niXzBPA1M=,tag:d2YKM1xDQngHFv9W4Dh3nQ==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:LS9DUD5BXjiWGqARa8UtFZc=,iv:gFJZ4njaUJPyzjPwQq1yeiB1G+ddYn7b2wWrRvxCusc=,tag:wH3Bf/M9QqoB5HbkotUe+g==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:EfhYqVGqpTBvrAVZRL/X30VlQg==,iv:Ogg+sCocmIkBGJQ0MiZQT8NHe00+9D0yWIqG961JBkw=,tag:IG+JnO+yuegBFig+m2RfPQ==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:+dKppChQb0oUynF3rul4UA==,iv:54wJPdxLkuERlTQxJV7PzK89VP4YgvUO59IZZRp2gp4=,tag:A56xuaJvyRNIo+OY0cKrRA==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:t/+7sD8E1FghmwkjkQ0dJjbvXphd,iv:n805GWQYA/2qJIYWqXcwbfG/tKZ5FQrBtiDf1uZSaZc=,tag:4GJeFtUWY8nEcMRjiERvrA==,type:str]
    huggingFaceToken: ENC[AES256_GCM,data:tPkI7uGevmk0jSohgjcEU39n6gwFqZu+N2aJVBKuoS7hH/pO+w==,iv:PLDeqxW779KsP3IyvSgxC3eQ8kz74j6wtQ2dz8VXW/I=,tag:7hqV407TZZA3mPBn++5ItA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1znw3q7j0drwhjyfvp5dmw59gpm5hrjc9lw3drpujslcjaky5veas2fmef4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NjZNWE9UODZPTXpYNW1O
            dEhKd3JzSFFoUHZzUEhRVTJwNGpoV2N3V3hFCjhNNzlZZ3NBSkZTcW1pcHNocnda
            dVBLbXhmUU42MFpJbTdCWHUzN09CUUkKLS0tIGhOV0FxRmdhbHFTMlNNMnVOYlpE
            cExyaFk0b0w4WDZ0VEVWVjJsWVk3NjQKO39KwaLLrLAHKNxXbdxP7sEFjTy6BZnd
            xyrlFHiQzZ2l2PX+n8Q3Rk4GZPYN7hzLS2LKAqMOrpnJO9Noy/sr8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-07T22:26:49Z"
    mac: ENC[AES256_GCM,data:hkk91o0Zy9vfAfJ8jpMw0vGRoHeZYXcVwf/BrNmu5Fg+N8aK1/ant2zvToNOkpjZ6+AKj1tuilRMEMtd5Whl8HMR3w7Hm3tczlxwAk8y4DjeHlHIRYSGFAphZWxPBm7odjEP2M9FJNZVzJEUZNxkXswYt9QRJjR+dHg2hSYeLZ0=,iv:FtKqww3SCvLImiENYasBDRCz6v/gcrUB0M9JWi+SLMM=,tag:Fq8hMIJITB3015dTvC4F0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
